import type { Deck } from "./types";

/**
 * Built-in demo deck so the studio (and the morph engine) can be tried
 * without an ANTHROPIC_API_KEY. Note the shared morphIds across slides:
 * "hero-title" shrinks into a kicker, "blob" travels as a motif, and the
 * stat card grows into a full-slide highlight.
 */
export const SAMPLE_DECK: Deck = {
  title: "The Morph Effect",
  subtitle: "Designing presentations that move",
  theme: {
    name: "Ember Editorial",
    background: "#101418",
    surface: "#1a2027",
    accent: "#ff6b4a",
    accent2: "#ffc46b",
    text: "#f4efe9",
    muted: "#8b949e",
    headingFont: "display",
    bodyFont: "sans",
  },
  slides: [
    {
      id: "s1",
      transition: "fade",
      background: null,
      notes:
        "Welcome everyone. This deck is itself a demo — watch how elements glide between slides instead of cutting. That continuous motion is the morph effect.",
      elements: [
        {
          id: "s1-blob",
          morphId: "blob",
          kind: "shape",
          text: null,
          items: null,
          label: null,
          x: 62,
          y: -18,
          w: 55,
          h: 70,
          color: null,
          bg: "#ff6b4a",
          fontSize: null,
          align: "left",
          radius: 500,
        },
        {
          id: "s1-kicker",
          morphId: null,
          kind: "kicker",
          text: "SLIDEMORPH AI · DEMO DECK",
          items: null,
          label: null,
          x: 8,
          y: 30,
          w: 50,
          h: 6,
          color: "#ffc46b",
          bg: null,
          fontSize: 15,
          align: "left",
          radius: null,
        },
        {
          id: "s1-title",
          morphId: "hero-title",
          kind: "heading",
          text: "The Morph Effect",
          items: null,
          label: null,
          x: 8,
          y: 38,
          w: 70,
          h: 24,
          color: null,
          bg: null,
          fontSize: 88,
          align: "left",
          radius: null,
        },
        {
          id: "s1-sub",
          morphId: null,
          kind: "subheading",
          text: "Designing presentations that move",
          items: null,
          label: null,
          x: 8,
          y: 64,
          w: 60,
          h: 8,
          color: "#8b949e",
          bg: null,
          fontSize: 28,
          align: "left",
          radius: null,
        },
      ],
    },
    {
      id: "s2",
      transition: "morph",
      background: null,
      notes:
        "The hero title just shrank into the top-left corner — same element, new role. The orange motif slid down-left. Three reasons motion matters.",
      elements: [
        {
          id: "s2-blob",
          morphId: "blob",
          kind: "shape",
          text: null,
          items: null,
          label: null,
          x: -14,
          y: 62,
          w: 34,
          h: 60,
          color: null,
          bg: "#ffc46b",
          fontSize: null,
          align: "left",
          radius: 500,
        },
        {
          id: "s2-title",
          morphId: "hero-title",
          kind: "kicker",
          text: "The Morph Effect",
          items: null,
          label: null,
          x: 6,
          y: 6,
          w: 30,
          h: 5,
          color: "#ff6b4a",
          bg: null,
          fontSize: 16,
          align: "left",
          radius: null,
        },
        {
          id: "s2-heading",
          morphId: null,
          kind: "heading",
          text: "Why motion matters",
          items: null,
          label: null,
          x: 6,
          y: 16,
          w: 70,
          h: 14,
          color: null,
          bg: null,
          fontSize: 56,
          align: "left",
          radius: null,
        },
        {
          id: "s2-bullets",
          morphId: null,
          kind: "bullets",
          text: null,
          items: [
            "Continuity shows how ideas relate",
            "Attention follows movement",
            "Polish signals credibility",
          ],
          label: null,
          x: 6,
          y: 36,
          w: 52,
          h: 40,
          color: null,
          bg: null,
          fontSize: 24,
          align: "left",
          radius: null,
        },
        {
          id: "s2-stat",
          morphId: "big-stat",
          kind: "stat",
          text: "6.5×",
          items: null,
          label: "more recall with visual continuity",
          x: 64,
          y: 36,
          w: 30,
          h: 34,
          color: "#ffc46b",
          bg: "#1a2027",
          fontSize: 64,
          align: "center",
          radius: 24,
        },
      ],
    },
    {
      id: "s3",
      transition: "morph",
      background: null,
      notes:
        "The stat card from the previous slide grew into the hero of this one — that's a morph on the same morphId. Land the number, then move on.",
      elements: [
        {
          id: "s3-blob",
          morphId: "blob",
          kind: "shape",
          text: null,
          items: null,
          label: null,
          x: 74,
          y: 70,
          w: 40,
          h: 52,
          color: null,
          bg: "#ff6b4a",
          fontSize: null,
          align: "left",
          radius: 500,
        },
        {
          id: "s3-stat",
          morphId: "big-stat",
          kind: "stat",
          text: "6.5×",
          items: null,
          label: "more recall when slides share moving elements",
          x: 14,
          y: 22,
          w: 72,
          h: 52,
          color: "#ffc46b",
          bg: "#1a2027",
          fontSize: 140,
          align: "center",
          radius: 32,
        },
        {
          id: "s3-kicker",
          morphId: null,
          kind: "kicker",
          text: "THE PAYOFF",
          items: null,
          label: null,
          x: 14,
          y: 12,
          w: 30,
          h: 5,
          color: "#8b949e",
          bg: null,
          fontSize: 15,
          align: "left",
          radius: null,
        },
      ],
    },
    {
      id: "s4",
      transition: "morph",
      background: null,
      notes:
        "How it works under the hood: Claude designs the deck as structured JSON, the browser renders it with shared-element transitions, and you can export a real PowerPoint file.",
      elements: [
        {
          id: "s4-blob",
          morphId: "blob",
          kind: "shape",
          text: null,
          items: null,
          label: null,
          x: 40,
          y: -22,
          w: 26,
          h: 40,
          color: null,
          bg: "#ffc46b",
          fontSize: null,
          align: "left",
          radius: 500,
        },
        {
          id: "s4-heading",
          morphId: null,
          kind: "heading",
          text: "How it works",
          items: null,
          label: null,
          x: 6,
          y: 10,
          w: 60,
          h: 14,
          color: null,
          bg: null,
          fontSize: 56,
          align: "left",
          radius: null,
        },
        {
          id: "s4-v1",
          morphId: null,
          kind: "visual",
          text: "🧠",
          items: null,
          label: "Claude designs layout, copy & theme",
          x: 6,
          y: 34,
          w: 27,
          h: 44,
          color: null,
          bg: "#1a2027",
          fontSize: null,
          align: "center",
          radius: 24,
        },
        {
          id: "s4-v2",
          morphId: null,
          kind: "visual",
          text: "🎬",
          items: null,
          label: "Morph engine animates shared elements",
          x: 36.5,
          y: 34,
          w: 27,
          h: 44,
          color: null,
          bg: "#1a2027",
          fontSize: null,
          align: "center",
          radius: 24,
        },
        {
          id: "s4-v3",
          morphId: null,
          kind: "visual",
          text: "📤",
          items: null,
          label: "Export a real .pptx file",
          x: 67,
          y: 34,
          w: 27,
          h: 44,
          color: null,
          bg: "#1a2027",
          fontSize: null,
          align: "center",
          radius: 24,
        },
      ],
    },
    {
      id: "s5",
      transition: "morph",
      background: "#ff6b4a",
      notes:
        "Close with the ask. The motif fills the frame — the same shape that traveled through the whole deck. Type your own topic and generate a deck.",
      elements: [
        {
          id: "s5-blob",
          morphId: "blob",
          kind: "shape",
          text: null,
          items: null,
          label: null,
          x: -30,
          y: -40,
          w: 160,
          h: 180,
          color: null,
          bg: "#ff6b4a",
          fontSize: null,
          align: "left",
          radius: 500,
        },
        {
          id: "s5-heading",
          morphId: null,
          kind: "heading",
          text: "Now make yours.",
          items: null,
          label: null,
          x: 10,
          y: 36,
          w: 80,
          h: 20,
          color: "#101418",
          bg: null,
          fontSize: 84,
          align: "center",
          radius: null,
        },
        {
          id: "s5-sub",
          morphId: null,
          kind: "subheading",
          text: "Type a topic → get a designed, animated deck",
          items: null,
          label: null,
          x: 15,
          y: 60,
          w: 70,
          h: 8,
          color: "#101418",
          bg: null,
          fontSize: 26,
          align: "center",
          radius: null,
        },
      ],
    },
  ],
};
